server:
  port: '8081'

spring:
  servlet:
    multipart:
      max-request-size: 4MB
      max-file-size: 4MB

aws:
  s3:
    download-folder: outbox
    bucket: public-api-djl-demo
    upload-folder: inbox

# djl:
#   app:
#     url: ${DJL_APP_URL:http://localhost:8080/classif-ai}



