version: '3.9'

#x-aws-vpc: "vpc-0013016b1dd63839b"
#x-aws-loadbalancer: "arn:aws:elasticloadbalancing:eu-west-1:809752095901:loadbalancer/app/apis-services-alb/06c6e35950e47268"

services:

  backend:
    image: zeguru/classifai-service:0.8
    container_name: classifai-backend
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: zeguru/classifai-frontend:0.5
    container_name: classifai-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: zeguru/classifai-nginx:0.6
    container_name: classifai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"

  
x-aws-cloudformation:
  Resources:
    NginxTCP80TargetGroup:
      Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
      Properties:
        HealthCheckProtocol: HTTP
        HealthCheckPath: /health
        Matcher:
          HttpCode: "200-299"