# Stage 2
FROM nginx

# copy the nginx configurations to the docker image
COPY ./nginx.build.conf /etc/nginx/nginx.conf



#Aftermath
#========================================

#Dockerize
#cd nginx
#docker build -t zeguru/classifai-nginx:0.4 .

#Push
#docker login
#docker push zeguru/classifai-nginx:0.4