<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Classif-AI Demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link media="all" rel="stylesheet" type="text/css" href="/style.css" />
</head>
<body style="padding-left: 1cm;">
    <h1>Deep Learning Engine</h1>
    <h2>Examples: Image Classification</h2>

    <a class="blue animate" href="image-classification/inbox">Image Classification</a>
    <br/>
    <a class="blue animate" href="video.html" >Video</a>
    <br/>
    <a class="blue animate" href="rtsp.html" >CCTV</a>
    <br/>
    <a class="blue animate" href="object-detection/inbox">Object Detection - not yet implemented</a>


</body>
</html>